"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import Navbar from './navbar'

import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const disabledNavbar = ["/login", "/register"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        {!disabledNavbar.includes(pathname) && <Navbar />}
        {/* <div>
          <h1>Layout {count}</h1>
          <button onClick={() => setCount(count + 1)}>+</button>
        </div> */}
        {children}
      </body>
    </html>
  )
}
